
# Default application configuration that all configurations inherit from.

scss_files: "sass/**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 3

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyRule:
    enabled: true

  LeadingZero:
    enabled: true
    style: include_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: false

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM

  StringQuotes:
    enabled: true
    style: single_quotes

  UrlQuotes:
    enabled: false

  VendorPrefix:
    enabled: false
